networks:
  private_network:
    name: private_network

services:
  web-api:
    image: battlewarriorxxl/web_api
    container_name: web-api
    build:
      dockerfile: CheckList/CheckList.Api/Dockerfile
    ports:
      - "3001:80"
    networks:
      - private_network
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ApplicationSettings__IdentityAuthority: http://identity-api
      ConnectionStrings__CheckListDbConntection: Server=sql-server;Database=CheckList;User Id=SA;Password=SomeSecretPassword12345;MultipleActiveResultSets=true;Trust Server Certificate=true

  identity-api:
    image: battlewarriorxxl/identity_api
    container_name: identity-api
    build:
      dockerfile: CheckList/Identity.Api/Dockerfile
    ports:
      - "3002:80"
    networks:
      - private_network
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ApplicationSettings__BaseAddress: http://identity-api
      ConnectionStrings__CheckListDbConntection: Server=sql-server;Database=CheckList;User Id=SA;Password=SomeSecretPassword12345;MultipleActiveResultSets=true;Trust Server Certificate=true

  client-react:
    image: battlewarriorxxl/react_client
    container_name: web-client
    build:
      dockerfile: checklist-front/Dockerfile
    ports:
      - "3000:80"
      
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    ports:
      - "1433:1433"
    networks:
      - private_network
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SomeSecretPassword12345"
